---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: kingdonb
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:kingdonb/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: kingdonb/podinfo
      tag: dev-c055kp1l
    service:
      annotations:
        dev.okteto.com/auto-ingress: "true"
    replicaCount: 1
    hpa:
      enabled: false
