---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-prod
  namespace: kingdonb
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.4
spec:
  releaseName: podinfo-prod
  chart:
    git: git@github.com:kingdonb/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: kingdonb/podinfo
      tag: 0.4.11
    service:
      annotations:
        dev.okteto.com/auto-ingress: "true"
    replicaCount: 3
